//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uyg03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int cartId { get; set; }
    
        public virtual Musteri Table { get; set; }
        public virtual SepetUrun SepetUrun { get; set; }
    }
}
