//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uyg03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SepetUrun
    {
        public int cartitemId { get; set; }
        public string cartitemName { get; set; }
    
        public virtual Sepet Sepet { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
